const map_platformfn = {
  'baseinfocompany':{
    'IPCType':'baseInfoCompany',
    'uri':'/baseinfo/company'
  },
  'baseinfocompanystat':{
    'IPCType':'baseInfoCompanyStat',
    'uri':'/baseinfo/companystat'
  },
  'baseinfocompanypay':{
    'IPCType':'baseInfoCompanyPay',
    'uri':'/baseinfo/companypay'
  },
  'baseinfocompanyservice':{
    'IPCType':'baseInfoCompanyService',
    'uri':'/baseinfo/companyservice'
  },
  'baseinfocompanypermit':{
    'IPCType':'baseInfoCompanyPermit',
    'uri':'/baseinfo/companypermit'
  },
  'baseinfocompanyfare':{
    'IPCType':'baseInfoCompanyFare',
    'uri':'/baseinfo/companyfare'
  },
  'baseinfovehicle':{
    'IPCType':'baseInfoVehicle',
    'uri':'/baseinfo/vehicle'
  },
  'baseinfovehicleinsurance':{
    'IPCType':'baseInfoVehicleInsurance',
    'uri':'/baseinfo/vehicleinsurance'
  },
  'baseinfovehicletotalmile':{
    'IPCType':'baseInfoVehicleTotalMile',
    'uri':'/baseinfo/vehicletotalmile'
  },
  'baseinfodriver':{
    'IPCType':'baseInfoDriver',
    'uri':'/baseinfo/driver'
  },
  'baseinfodrivereducate':{
    'IPCType':'baseInfoDriverEducate',
    'uri':'/baseinfo/drivereducate'
  },
  'baseinfodriverapp':{
    'IPCType':'baseInfoDriverApp',
    'uri':'/baseinfo/driverapp'
  },
  'baseinfodriverstat':{
    'IPCType':'baseInfoDriverStat',
    'uri':'/baseinfo/driverstat'
  },
  'baseinfopassenger':{
    'IPCType':'baseInfoPassenger',
    'uri':'/baseinfo/passenger'
  },

  'ordercreate':{
    'IPCType':'orderCreate',
    'uri':'/order/create'
  },
  'ordermatch':{
    'IPCType':'orderMatch',
    'uri':'/order/match'
  },
  'ordercancel':{
    'IPCType':'orderCancel',
    'uri':'/order/cancel'
  },


  'operatelogin':{
    'IPCType':'operateLogin',
    'uri':'/operate/login'
  },
  'operatelogout':{
    'IPCType':'operateLogout',
    'uri':'/operate/logout'
  },
  'operatedepart':{
    'IPCType':'operateDepart',
    'uri':'/operate/depart'
  },
  'operatearrive':{
    'IPCType':'operateArrive',
    'uri':'/operate/arrive'
  },
  'operatepay':{
    'IPCType':'operatePay',
    'uri':'/operate/pay'
  },


  'positiondriver':{
    'IPCType':'positionDriver',
    'uri':'/position/driver'
  },
  'positionvehicle':{
    'IPCType':'positionVehicle',
    'uri':'/position/vehicle'
  },


  'ratedpassenger':{
    'IPCType':'ratedPassenger',
    'uri':'/rated/passenger'
  },
  'ratedpassengercomplaint':{
    'IPCType':'ratedPassengerComplaint',
    'uri':'/rated/passengercomplaint'
  },
  'rateddriverpunish':{
    'IPCType':'ratedDriverPunish',
    'uri':'/rated/driverpunish'
  },
  'rateddriver':{
    'IPCType':'ratedDriver',
    'uri':'/rated/driver'
  },
};


module.exports = map_platformfn;
