
export const getcontactlist = (funcb)=>{
  let datas = [];
  datas.push(
      {
        key:'A',
        datas:[
            {
              name:'阿娇',
              phone:'15961125161'
            },
            {
              name:'阿加',
              phone:'15961125162'
            }
        ]
      }
    );
    datas.push(
      {
        key:'B',
        datas:[
            {
              name:'包工头',
              phone:'15961125161'
            },
            {
              name:'包文去',
              phone:'15961125162'
            }
        ]
      }
    );
    datas.push(
      {
        key:'C',
        datas:[
            {
              name:'常为',
              phone:'15961125161'
            },
            {
              name:'车加想',
              phone:'15961125162'
            }
        ]
      }
    );
    datas.push(
      {
        key:'D',
        datas:[
            {
              name:'弟弟',
              phone:'15961125161'
            },
            {
              name:'狄文',
              phone:'15961125162'
            }
        ]
      }
    );
    datas.push(
      {
        key:'W',
        datas:[
            {
              name:'微信群',
              phone:'15961125161'
            },
            {
              name:'雯雯',
              phone:'15961125162'
            }
        ]
      }
    );
    funcb(datas);
}
